services:
  # database:
  #   image: postgres:16.3-alpine3.20
  #   container_name: database
  #   environment:
  #     POSTGRES_DB: university
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 12345
      
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./database/sample.sql:/docker-entrypoint-initdb.d/sample.sql
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: university
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/sample.sql:/docker-entrypoint-initdb.d/sample.sql

  server:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /home/bun/app
    volumes:
      - ./frontend:/home/bun/app
      - /home/bun/app/node_modules
    expose:
      - "5173"
    ports:
      - "5173:5173"
    restart: always
    # depends_on:
    #   - server
  